
# Auto generated by component_builder.cpp

builder : component_builder.cpp
	$(CXX) -Wall -std=c++17 -O3 component_builder.cpp -o builder


flags = g++ -Wall -Wextra -O0 -ggdb3

headers = components.hpp core/configuration.hpp core/experiments.hpp core/analysis.hpp core/utilities/csv/csv.hpp core/utilities/csv/csv_reader.hpp core/utilities/term_colours.hpp core/utilities/utilities.hpp core/language/token.hpp core/language/lexer.hpp core/language/parser.hpp core/specs/configuration_primitive.hpp core/specs/signal_spec.hpp core/specs/population_spec.hpp core/specs/substrate_spec.hpp core/specs/process_spec.hpp core/specs/converter_spec.hpp core/specs/encoding_spec.hpp core/concepts/substrate.hpp core/concepts/process.hpp core/concepts/population.hpp core/concepts/converter.hpp core/concepts/signal.hpp core/concepts/encoding.hpp 

components = obj_files/main.o obj_files/components.o obj_files/core_configuration.o obj_files/core_experiments.o obj_files/core_analysis.o obj_files/core_utilities_csv_csv.o obj_files/core_utilities_csv_csv_reader.o obj_files/core_utilities_term_colours.o obj_files/core_utilities_utilities.o obj_files/core_language_token.o obj_files/core_language_lexer.o obj_files/core_language_parser.o obj_files/core_specs_configuration_primitive.o obj_files/core_specs_signal_spec.o obj_files/core_specs_population_spec.o obj_files/core_specs_substrate_spec.o obj_files/core_specs_process_spec.o obj_files/core_specs_converter_spec.o obj_files/core_specs_encoding_spec.o obj_files/core_concepts_substrate.o obj_files/core_concepts_process.o obj_files/core_concepts_population.o obj_files/core_concepts_converter.o obj_files/core_concepts_signal.o obj_files/core_concepts_encoding.o obj_files/user_converter_vd_vb_vd_vb.o obj_files/user_converter_vb_vd_vb_vd.o obj_files/user_converter_add_add.o obj_files/user_converter_slice_slice.o obj_files/user_population_null_population_null_population.o obj_files/user_population_linear_linear.o obj_files/user_process_null_process_null_process.o obj_files/user_process_forager_forager.o obj_files/user_process_max_one_max_one.o obj_files/user_process_replicate_replicate.o obj_files/user_process_logic_9_logic_9.o obj_files/user_process_elite_replacement_elite_replacement.o obj_files/user_process_cycle_cycle.o obj_files/user_process_sequence_sequence.o obj_files/user_process_roulette_wheel_roulette_wheel.o obj_files/user_process_fork_join_fork_join.o obj_files/user_substrate_null_substrate_null_substrate.o obj_files/user_substrate_markov_brain_markov_brain.o 

ded : $(components)
	$(flags) $(components) -lstdc++fs -o ded

obj_files/main.o : main.cpp 
	$(flags) -c main.cpp -o obj_files/main.o

obj_files/core_configuration.o : core/configuration.cpp 
	$(flags) -c core/configuration.cpp  -o obj_files/core_configuration.o 

obj_files/core_experiments.o : core/experiments.cpp 
	$(flags) -c core/experiments.cpp  -o obj_files/core_experiments.o 

obj_files/core_analysis.o : core/analysis.cpp 
	$(flags) -c core/analysis.cpp  -o obj_files/core_analysis.o 

obj_files/core_utilities_csv_csv.o : core/utilities/csv/csv.cpp 
	$(flags) -c core/utilities/csv/csv.cpp  -o obj_files/core_utilities_csv_csv.o 

obj_files/core_utilities_csv_csv_reader.o : core/utilities/csv/csv_reader.cpp 
	$(flags) -c core/utilities/csv/csv_reader.cpp  -o obj_files/core_utilities_csv_csv_reader.o 

obj_files/core_utilities_term_colours.o : core/utilities/term_colours.cpp 
	$(flags) -c core/utilities/term_colours.cpp  -o obj_files/core_utilities_term_colours.o 

obj_files/core_utilities_utilities.o : core/utilities/utilities.cpp 
	$(flags) -c core/utilities/utilities.cpp  -o obj_files/core_utilities_utilities.o 

obj_files/core_language_token.o : core/language/token.cpp 
	$(flags) -c core/language/token.cpp  -o obj_files/core_language_token.o 

obj_files/core_language_lexer.o : core/language/lexer.cpp 
	$(flags) -c core/language/lexer.cpp  -o obj_files/core_language_lexer.o 

obj_files/core_language_parser.o : core/language/parser.cpp 
	$(flags) -c core/language/parser.cpp  -o obj_files/core_language_parser.o 

obj_files/core_specs_configuration_primitive.o : core/specs/configuration_primitive.cpp 
	$(flags) -c core/specs/configuration_primitive.cpp  -o obj_files/core_specs_configuration_primitive.o 

obj_files/core_specs_signal_spec.o : core/specs/signal_spec.cpp 
	$(flags) -c core/specs/signal_spec.cpp  -o obj_files/core_specs_signal_spec.o 

obj_files/core_specs_population_spec.o : core/specs/population_spec.cpp 
	$(flags) -c core/specs/population_spec.cpp  -o obj_files/core_specs_population_spec.o 

obj_files/core_specs_substrate_spec.o : core/specs/substrate_spec.cpp 
	$(flags) -c core/specs/substrate_spec.cpp  -o obj_files/core_specs_substrate_spec.o 

obj_files/core_specs_process_spec.o : core/specs/process_spec.cpp 
	$(flags) -c core/specs/process_spec.cpp  -o obj_files/core_specs_process_spec.o 

obj_files/core_specs_converter_spec.o : core/specs/converter_spec.cpp 
	$(flags) -c core/specs/converter_spec.cpp  -o obj_files/core_specs_converter_spec.o 

obj_files/core_specs_encoding_spec.o : core/specs/encoding_spec.cpp 
	$(flags) -c core/specs/encoding_spec.cpp  -o obj_files/core_specs_encoding_spec.o 

obj_files/core_concepts_substrate.o : core/concepts/substrate.cpp 
	$(flags) -c core/concepts/substrate.cpp  -o obj_files/core_concepts_substrate.o 

obj_files/core_concepts_process.o : core/concepts/process.cpp 
	$(flags) -c core/concepts/process.cpp  -o obj_files/core_concepts_process.o 

obj_files/core_concepts_population.o : core/concepts/population.cpp 
	$(flags) -c core/concepts/population.cpp  -o obj_files/core_concepts_population.o 

obj_files/core_concepts_converter.o : core/concepts/converter.cpp 
	$(flags) -c core/concepts/converter.cpp  -o obj_files/core_concepts_converter.o 

obj_files/core_concepts_signal.o : core/concepts/signal.cpp 
	$(flags) -c core/concepts/signal.cpp  -o obj_files/core_concepts_signal.o 

obj_files/core_concepts_encoding.o : core/concepts/encoding.cpp 
	$(flags) -c core/concepts/encoding.cpp  -o obj_files/core_concepts_encoding.o 

obj_files/components.o : components.cpp $(headers) user/converter/vd_vb/vd_vb.hpp user/converter/vb_vd/vb_vd.hpp user/converter/add/add.hpp user/converter/slice/slice.hpp user/population/null_population/null_population.hpp user/population/linear/linear.hpp user/process/null_process/null_process.hpp user/process/forager/forager.hpp user/process/max_one/max_one.hpp user/process/replicate/replicate.hpp user/process/logic_9/logic_9.hpp user/process/elite_replacement/elite_replacement.hpp user/process/cycle/cycle.hpp user/process/sequence/sequence.hpp user/process/roulette_wheel/roulette_wheel.hpp user/process/fork_join/fork_join.hpp user/substrate/null_substrate/null_substrate.hpp user/substrate/markov_brain/markov_brain.hpp 
	$(flags) -c components.cpp -o obj_files/components.o

obj_files/user_converter_vd_vb_vd_vb.o : user/converter/vd_vb/vd_vb.cpp user/converter/vd_vb/vd_vb.hpp  $(headers) 
	$(flags) -c user/converter/vd_vb/vd_vb.cpp -o obj_files/user_converter_vd_vb_vd_vb.o 

obj_files/user_converter_vb_vd_vb_vd.o : user/converter/vb_vd/vb_vd.cpp user/converter/vb_vd/vb_vd.hpp  $(headers) 
	$(flags) -c user/converter/vb_vd/vb_vd.cpp -o obj_files/user_converter_vb_vd_vb_vd.o 

obj_files/user_converter_add_add.o : user/converter/add/add.cpp user/converter/add/add.hpp  $(headers) 
	$(flags) -c user/converter/add/add.cpp -o obj_files/user_converter_add_add.o 

obj_files/user_converter_slice_slice.o : user/converter/slice/slice.cpp user/converter/slice/slice.hpp  $(headers) 
	$(flags) -c user/converter/slice/slice.cpp -o obj_files/user_converter_slice_slice.o 

obj_files/user_population_null_population_null_population.o : user/population/null_population/null_population.cpp user/population/null_population/null_population.hpp  $(headers) 
	$(flags) -c user/population/null_population/null_population.cpp -o obj_files/user_population_null_population_null_population.o 

obj_files/user_population_linear_linear.o : user/population/linear/linear.cpp user/population/linear/linear.hpp  $(headers) 
	$(flags) -c user/population/linear/linear.cpp -o obj_files/user_population_linear_linear.o 

obj_files/user_process_null_process_null_process.o : user/process/null_process/null_process.cpp user/process/null_process/null_process.hpp  $(headers) 
	$(flags) -c user/process/null_process/null_process.cpp -o obj_files/user_process_null_process_null_process.o 

obj_files/user_process_forager_forager.o : user/process/forager/forager.cpp user/process/forager/forager.hpp  $(headers) 
	$(flags) -c user/process/forager/forager.cpp -o obj_files/user_process_forager_forager.o 

obj_files/user_process_max_one_max_one.o : user/process/max_one/max_one.cpp user/process/max_one/max_one.hpp  $(headers) 
	$(flags) -c user/process/max_one/max_one.cpp -o obj_files/user_process_max_one_max_one.o 

obj_files/user_process_replicate_replicate.o : user/process/replicate/replicate.cpp user/process/replicate/replicate.hpp  $(headers) 
	$(flags) -c user/process/replicate/replicate.cpp -o obj_files/user_process_replicate_replicate.o 

obj_files/user_process_logic_9_logic_9.o : user/process/logic_9/logic_9.cpp user/process/logic_9/logic_9.hpp  $(headers) 
	$(flags) -c user/process/logic_9/logic_9.cpp -o obj_files/user_process_logic_9_logic_9.o 

obj_files/user_process_elite_replacement_elite_replacement.o : user/process/elite_replacement/elite_replacement.cpp user/process/elite_replacement/elite_replacement.hpp  $(headers) 
	$(flags) -c user/process/elite_replacement/elite_replacement.cpp -o obj_files/user_process_elite_replacement_elite_replacement.o 

obj_files/user_process_cycle_cycle.o : user/process/cycle/cycle.cpp user/process/cycle/cycle.hpp  $(headers) 
	$(flags) -c user/process/cycle/cycle.cpp -o obj_files/user_process_cycle_cycle.o 

obj_files/user_process_sequence_sequence.o : user/process/sequence/sequence.cpp user/process/sequence/sequence.hpp  $(headers) 
	$(flags) -c user/process/sequence/sequence.cpp -o obj_files/user_process_sequence_sequence.o 

obj_files/user_process_roulette_wheel_roulette_wheel.o : user/process/roulette_wheel/roulette_wheel.cpp user/process/roulette_wheel/roulette_wheel.hpp  $(headers) 
	$(flags) -c user/process/roulette_wheel/roulette_wheel.cpp -o obj_files/user_process_roulette_wheel_roulette_wheel.o 

obj_files/user_process_fork_join_fork_join.o : user/process/fork_join/fork_join.cpp user/process/fork_join/fork_join.hpp  $(headers) 
	$(flags) -c user/process/fork_join/fork_join.cpp -o obj_files/user_process_fork_join_fork_join.o 

obj_files/user_substrate_null_substrate_null_substrate.o : user/substrate/null_substrate/null_substrate.cpp user/substrate/null_substrate/null_substrate.hpp  $(headers) 
	$(flags) -c user/substrate/null_substrate/null_substrate.cpp -o obj_files/user_substrate_null_substrate_null_substrate.o 

obj_files/user_substrate_markov_brain_markov_brain.o : user/substrate/markov_brain/markov_brain.cpp user/substrate/markov_brain/markov_brain.hpp  $(headers) 
	$(flags) -c user/substrate/markov_brain/markov_brain.cpp -o obj_files/user_substrate_markov_brain_markov_brain.o 


clean : 
	rm -f obj_files/*.o
	rm -f ded

