
# Auto generated by component_builder.cpp

builder : component_builder.cpp
	$(CXX) -Wall -std=c++17 -O3 component_builder.cpp -o builder


flags = g++-7 -Wall -Wextra -std=c++17 -O0 -ggdb3 

headers = components.hpp core/configuration.hpp core/experiments.hpp core/analysis.hpp core/utilities/csv/csv.hpp core/utilities/csv/csv_reader.hpp core/utilities/term_colours.hpp core/utilities/utilities.hpp core/language/token.hpp core/language/lexer.hpp core/language/parser.hpp core/specs/configuration_primitive.hpp core/specs/signal_spec.hpp core/specs/population_spec.hpp core/specs/substrate_spec.hpp core/specs/process_spec.hpp core/specs/encoding_spec.hpp core/concepts/substrate.hpp core/concepts/process.hpp core/concepts/population.hpp core/concepts/signal.hpp core/concepts/encoding.hpp 

components = obj_files/main.o obj_files/components.o obj_files/core_configuration.o obj_files/core_experiments.o obj_files/core_analysis.o obj_files/core_utilities_csv_csv.o obj_files/core_utilities_csv_csv_reader.o obj_files/core_utilities_term_colours.o obj_files/core_utilities_utilities.o obj_files/core_language_token.o obj_files/core_language_lexer.o obj_files/core_language_parser.o obj_files/core_specs_configuration_primitive.o obj_files/core_specs_signal_spec.o obj_files/core_specs_population_spec.o obj_files/core_specs_substrate_spec.o obj_files/core_specs_process_spec.o obj_files/core_specs_encoding_spec.o obj_files/core_concepts_substrate.o obj_files/core_concepts_process.o obj_files/core_concepts_population.o obj_files/core_concepts_signal.o obj_files/core_concepts_encoding.o obj_files/user_Population_null_population_null_population.o obj_files/user_Population_linear_linear.o obj_files/user_Process_null_process_null_process.o obj_files/user_Process_forager_forager.o obj_files/user_Process_forager_bf_forager_bf.o obj_files/user_Process_max_one_max_one.o obj_files/user_Process_replicate_replicate.o obj_files/user_Process_elite_replacement_elite_replacement.o obj_files/user_Process_cycle_cycle.o obj_files/user_Process_sequence_sequence.o obj_files/user_Process_roulette_wheel_roulette_wheel.o obj_files/user_Process_fork_join_fork_join.o obj_files/user_Substrate_null_substrate_null_substrate.o obj_files/user_Substrate_markov_brain_markov_brain.o obj_files/user_Substrate_det_logic_det_logic.o obj_files/user_Substrate_buffet_buffet.o obj_files/user_Substrate_markov_brain_indirect_markov_brain_indirect.o obj_files/user_Substrate_markov_brain_bf_markov_brain_bf.o obj_files/user_Substrate_cppn_cppn.o 

ded : $(components)
	$(flags) $(components) -lstdc++fs -o ded

obj_files/main.o : main.cpp 
	$(flags) -c main.cpp -o obj_files/main.o

obj_files/core_configuration.o : core/configuration.cpp 
	$(flags) -c core/configuration.cpp  -o obj_files/core_configuration.o 

obj_files/core_experiments.o : core/experiments.cpp 
	$(flags) -c core/experiments.cpp  -o obj_files/core_experiments.o 

obj_files/core_analysis.o : core/analysis.cpp 
	$(flags) -c core/analysis.cpp  -o obj_files/core_analysis.o 

obj_files/core_utilities_csv_csv.o : core/utilities/csv/csv.cpp 
	$(flags) -c core/utilities/csv/csv.cpp  -o obj_files/core_utilities_csv_csv.o 

obj_files/core_utilities_csv_csv_reader.o : core/utilities/csv/csv_reader.cpp 
	$(flags) -c core/utilities/csv/csv_reader.cpp  -o obj_files/core_utilities_csv_csv_reader.o 

obj_files/core_utilities_term_colours.o : core/utilities/term_colours.cpp 
	$(flags) -c core/utilities/term_colours.cpp  -o obj_files/core_utilities_term_colours.o 

obj_files/core_utilities_utilities.o : core/utilities/utilities.cpp 
	$(flags) -c core/utilities/utilities.cpp  -o obj_files/core_utilities_utilities.o 

obj_files/core_language_token.o : core/language/token.cpp 
	$(flags) -c core/language/token.cpp  -o obj_files/core_language_token.o 

obj_files/core_language_lexer.o : core/language/lexer.cpp 
	$(flags) -c core/language/lexer.cpp  -o obj_files/core_language_lexer.o 

obj_files/core_language_parser.o : core/language/parser.cpp 
	$(flags) -c core/language/parser.cpp  -o obj_files/core_language_parser.o 

obj_files/core_specs_configuration_primitive.o : core/specs/configuration_primitive.cpp 
	$(flags) -c core/specs/configuration_primitive.cpp  -o obj_files/core_specs_configuration_primitive.o 

obj_files/core_specs_signal_spec.o : core/specs/signal_spec.cpp 
	$(flags) -c core/specs/signal_spec.cpp  -o obj_files/core_specs_signal_spec.o 

obj_files/core_specs_population_spec.o : core/specs/population_spec.cpp 
	$(flags) -c core/specs/population_spec.cpp  -o obj_files/core_specs_population_spec.o 

obj_files/core_specs_substrate_spec.o : core/specs/substrate_spec.cpp 
	$(flags) -c core/specs/substrate_spec.cpp  -o obj_files/core_specs_substrate_spec.o 

obj_files/core_specs_process_spec.o : core/specs/process_spec.cpp 
	$(flags) -c core/specs/process_spec.cpp  -o obj_files/core_specs_process_spec.o 

obj_files/core_specs_encoding_spec.o : core/specs/encoding_spec.cpp 
	$(flags) -c core/specs/encoding_spec.cpp  -o obj_files/core_specs_encoding_spec.o 

obj_files/core_concepts_substrate.o : core/concepts/substrate.cpp 
	$(flags) -c core/concepts/substrate.cpp  -o obj_files/core_concepts_substrate.o 

obj_files/core_concepts_process.o : core/concepts/process.cpp 
	$(flags) -c core/concepts/process.cpp  -o obj_files/core_concepts_process.o 

obj_files/core_concepts_population.o : core/concepts/population.cpp 
	$(flags) -c core/concepts/population.cpp  -o obj_files/core_concepts_population.o 

obj_files/core_concepts_signal.o : core/concepts/signal.cpp 
	$(flags) -c core/concepts/signal.cpp  -o obj_files/core_concepts_signal.o 

obj_files/core_concepts_encoding.o : core/concepts/encoding.cpp 
	$(flags) -c core/concepts/encoding.cpp  -o obj_files/core_concepts_encoding.o 

obj_files/components.o : components.cpp $(headers) user/Population/null_population/null_population.hpp user/Population/linear/linear.hpp user/Process/null_process/null_process.hpp user/Process/forager/forager.hpp user/Process/forager_bf/forager_bf.hpp user/Process/max_one/max_one.hpp user/Process/replicate/replicate.hpp user/Process/elite_replacement/elite_replacement.hpp user/Process/cycle/cycle.hpp user/Process/sequence/sequence.hpp user/Process/roulette_wheel/roulette_wheel.hpp user/Process/fork_join/fork_join.hpp user/Substrate/null_substrate/null_substrate.hpp user/Substrate/markov_brain/markov_brain.hpp user/Substrate/det_logic/det_logic.hpp user/Substrate/buffet/buffet.hpp user/Substrate/markov_brain_indirect/markov_brain_indirect.hpp user/Substrate/markov_brain_bf/markov_brain_bf.hpp user/Substrate/cppn/cppn.hpp 
	$(flags) -c components.cpp -o obj_files/components.o

obj_files/user_Population_null_population_null_population.o : user/Population/null_population/null_population.cpp user/Population/null_population/null_population.hpp  $(headers) 
	$(flags) -c user/Population/null_population/null_population.cpp -o obj_files/user_Population_null_population_null_population.o 

obj_files/user_Population_linear_linear.o : user/Population/linear/linear.cpp user/Population/linear/linear.hpp  $(headers) 
	$(flags) -c user/Population/linear/linear.cpp -o obj_files/user_Population_linear_linear.o 

obj_files/user_Process_null_process_null_process.o : user/Process/null_process/null_process.cpp user/Process/null_process/null_process.hpp  $(headers) 
	$(flags) -c user/Process/null_process/null_process.cpp -o obj_files/user_Process_null_process_null_process.o 

obj_files/user_Process_forager_forager.o : user/Process/forager/forager.cpp user/Process/forager/forager.hpp  $(headers) 
	$(flags) -c user/Process/forager/forager.cpp -o obj_files/user_Process_forager_forager.o 

obj_files/user_Process_forager_bf_forager_bf.o : user/Process/forager_bf/forager_bf.cpp user/Process/forager_bf/forager_bf.hpp  $(headers) 
	$(flags) -c user/Process/forager_bf/forager_bf.cpp -o obj_files/user_Process_forager_bf_forager_bf.o 

obj_files/user_Process_max_one_max_one.o : user/Process/max_one/max_one.cpp user/Process/max_one/max_one.hpp  $(headers) 
	$(flags) -c user/Process/max_one/max_one.cpp -o obj_files/user_Process_max_one_max_one.o 

obj_files/user_Process_replicate_replicate.o : user/Process/replicate/replicate.cpp user/Process/replicate/replicate.hpp  $(headers) 
	$(flags) -c user/Process/replicate/replicate.cpp -o obj_files/user_Process_replicate_replicate.o 

obj_files/user_Process_elite_replacement_elite_replacement.o : user/Process/elite_replacement/elite_replacement.cpp user/Process/elite_replacement/elite_replacement.hpp  $(headers) 
	$(flags) -c user/Process/elite_replacement/elite_replacement.cpp -o obj_files/user_Process_elite_replacement_elite_replacement.o 

obj_files/user_Process_cycle_cycle.o : user/Process/cycle/cycle.cpp user/Process/cycle/cycle.hpp  $(headers) 
	$(flags) -c user/Process/cycle/cycle.cpp -o obj_files/user_Process_cycle_cycle.o 

obj_files/user_Process_sequence_sequence.o : user/Process/sequence/sequence.cpp user/Process/sequence/sequence.hpp  $(headers) 
	$(flags) -c user/Process/sequence/sequence.cpp -o obj_files/user_Process_sequence_sequence.o 

obj_files/user_Process_roulette_wheel_roulette_wheel.o : user/Process/roulette_wheel/roulette_wheel.cpp user/Process/roulette_wheel/roulette_wheel.hpp  $(headers) 
	$(flags) -c user/Process/roulette_wheel/roulette_wheel.cpp -o obj_files/user_Process_roulette_wheel_roulette_wheel.o 

obj_files/user_Process_fork_join_fork_join.o : user/Process/fork_join/fork_join.cpp user/Process/fork_join/fork_join.hpp  $(headers) 
	$(flags) -c user/Process/fork_join/fork_join.cpp -o obj_files/user_Process_fork_join_fork_join.o 

obj_files/user_Substrate_null_substrate_null_substrate.o : user/Substrate/null_substrate/null_substrate.cpp user/Substrate/null_substrate/null_substrate.hpp  $(headers) 
	$(flags) -c user/Substrate/null_substrate/null_substrate.cpp -o obj_files/user_Substrate_null_substrate_null_substrate.o 

obj_files/user_Substrate_markov_brain_markov_brain.o : user/Substrate/markov_brain/markov_brain.cpp user/Substrate/markov_brain/markov_brain.hpp  $(headers) 
	$(flags) -c user/Substrate/markov_brain/markov_brain.cpp -o obj_files/user_Substrate_markov_brain_markov_brain.o 

obj_files/user_Substrate_det_logic_det_logic.o : user/Substrate/det_logic/det_logic.cpp user/Substrate/det_logic/det_logic.hpp  $(headers) 
	$(flags) -c user/Substrate/det_logic/det_logic.cpp -o obj_files/user_Substrate_det_logic_det_logic.o 

obj_files/user_Substrate_buffet_buffet.o : user/Substrate/buffet/buffet.cpp user/Substrate/buffet/buffet.hpp  $(headers) 
	$(flags) -c user/Substrate/buffet/buffet.cpp -o obj_files/user_Substrate_buffet_buffet.o 

obj_files/user_Substrate_markov_brain_indirect_markov_brain_indirect.o : user/Substrate/markov_brain_indirect/markov_brain_indirect.cpp user/Substrate/markov_brain_indirect/markov_brain_indirect.hpp  $(headers) 
	$(flags) -c user/Substrate/markov_brain_indirect/markov_brain_indirect.cpp -o obj_files/user_Substrate_markov_brain_indirect_markov_brain_indirect.o 

obj_files/user_Substrate_markov_brain_bf_markov_brain_bf.o : user/Substrate/markov_brain_bf/markov_brain_bf.cpp user/Substrate/markov_brain_bf/markov_brain_bf.hpp  $(headers) 
	$(flags) -c user/Substrate/markov_brain_bf/markov_brain_bf.cpp -o obj_files/user_Substrate_markov_brain_bf_markov_brain_bf.o 

obj_files/user_Substrate_cppn_cppn.o : user/Substrate/cppn/cppn.cpp user/Substrate/cppn/cppn.hpp  $(headers) 
	$(flags) -c user/Substrate/cppn/cppn.cpp -o obj_files/user_Substrate_cppn_cppn.o 


clean : 
	rm -f obj_files/*.o
	rm -f ded

