

# no way to turn off mutations? :(

e = $markov_brain 
	{	
		outputs =  ^env-length 
		#outputs =  8
	}

pop = $linear 
	{ 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
	}

correct_pop = !pop { size = 25 }

empty_pop = !pop { size = 1 }

Population = [ !correct_pop !empty_pop ]
#Population =  !empty_pop 

env = 	$max_one 	
		{ 
			? ones 1 
		    length = 8
		}

no_diff_selection = $sequence  
{
	 first = !env
     second = $elite_replacement  {  strength = 0.01  }
}


correct_env = $sequence  
{
	 first = !env
     second = $elite_replacement  {  strength = 0.4  }
}


Process = $cycle  { 
 count = 101
  world = [ !correct_env !no_diff_selection ]
}

