
# working

c = $cppn {
     hiddens =  2  
	 outputs =  1
	 inputs = 2
	}

e = $markov_brain_regular_cppn {
     #hiddens =  [ 2 3 ] 
	 outputs =  2
	 inputs = 4
	 cppn = !c
	}

Population = $linear { 
	size = 10 
	entity = !e # `entity` is special
	track_lineage = true 
	}



fors = $sequence  
{
     first 	= 	$forager 	
				{ 
				  ? food_eaten 5 
			      #replace = [ true false ]   
				}
     second = $elite_replacement 
			  {  strength = 0.1  
				  #? value 5 
			  }
}


Process = $cycle  { 
 count = 101
  world = !fors
}

