
# working

e = $markov_brain {
     hiddens = 5
	 outputs = 2
	 inputs = 4
	}

P = $linear { 
	size = 40
	entity = !e # `entity` is special
	track_lineage = true 
	}



fs = 
  $sequence  {
     first 	= 		$forager { ? food_eaten 7 }
     second = $elite_replacement { 
 	 strength = 	0.4 
  }
}

epoch = $cycle  { 
 count = 100
  world = !fs
}

# lineage tracking gets turned off here
E = $sequence {
	first = !epoch
    second 	= !epoch
			{ count = 25 }
}
