
# working

e = $markov_brain {
     hiddens =   2 
	 outputs =  2
	 inputs = 4
	}

P = $linear { 
	size = 50 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
	}



fors = $sequence  
{
     first 	= 	$forager 	
				{ 
				  ? food_eaten 5 
			      #replace = [ true false ]   
				}
     second = $elite_replacement  {  strength = 0.4  }
}


E = $cycle  { 
 count = 101
  world = !fors
}

