
# working

enc = $encoding 
{
	point_mutate_prob =  0.005 
}

e = $markov_brain 
{
     hiddens =   [ 2 3 4 ] 
	 outputs =  2 
	 inputs = 4
	 genome = !enc
}

Population = $linear 
{ 
	size = 50 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
}



fors = $sequence  
{
     first 	= 	$forager 	
				{ 
				  ? food_eaten 5 
				}
     second = $elite_replacement  {  strength = 0.4 }
}


Process = $cycle  { 
 count = 101
  world = !fors
}

