
# working

e = $markov_brain {
     hiddens =  [ 2 3 ] 
	 outputs =  2
	 inputs = 4
	}

P = $linear { 
	size = 100 
	entity = !e # `entity` is special
	track_lineage = true 
	}



fors = $sequence  
{
     first 	= 	$forager 	
				{ 
				  #? food_eaten 5 
			      #replace = [ true false ]   
				}
     second = $elite_replacement 
			  {  strength = 0.1  
				  ? value 5 }
}


E = $cycle  { 
 count = 1001
  world = !fors
}

