
# working

e = $markov_brain {
     hiddens = 5
	 outputs = 2
	 inputs = 4
	}

Population = $linear { 
	size = [ 20 40 60 80 ]
	entity = !e # `entity` is special
	track_lineage = true 
	}



fs = 
  $sequence  {
     first 	= 		$forager { ? food_eaten 7 }
     second = $elite_replacement { 
 	 strength = 	0.4 
  }
}

epoch = $cycle  { 
  world = !fs
}

# lineage tracking gets turned off here
Process = $sequence {
	first = !epoch
			{ count = 100 }
    second 	= !epoch
			{ count = 25 }
}
