

e = $markov_brain {
     hiddens = 5
	 outputs = 2
	 inputs = 4
	}

P = $linear 
	{ 
	size = 40
	entity = !e # `entity` is special
	track_lineage = true 
	}

rep_for = $replicate 
	{
		num = [ 1 2 3 ]
		env = $forager 
				{ ? food_eaten 3 }
		? x 10 
	}

fs = 
  $sequence  {
     first 	= !rep_for 
     second = $elite_replacement { 
 	 strength = 0.4   
  }
}


E = $cycle  { 
 count = 101
  world = !fs
}

