

e = $markov_brain 
 {
     hiddens = 5
	 outputs = 2
	 inputs = 4
 }

P = $linear 
 { 
	size = 40
	entity = !e # `entity` is special
	track_lineage = true 
 }

 night = $cycle 
 {
 	count = 10
  	world = $sequence 
	{
		first = $forager { replace = false }
		second = $elite_replacement 
		{ 
			? value 5 
		}
	}
 }

day = $cycle 
 {
 	count = 10
  	world = $sequence 
	{
		first = $forager { replace = true }
     	second = $elite_replacement  
		{ 
			? value 5 
		}
	}
 }

day_night = $sequence 
 {
	first = !day
	second = !night
 }


E = $cycle  
 { 
  count = 40
  world = !day_night
 }

