
# example of a composite brain
# buffet brain contains gates (that are just substrates)
# and wiring of the buffet brain is similar  
# to a markov brain

__substrate logic =  $det_logic
{
     hiddens =   2 
   outputs =  2
   inputs = 4
}
   
__substrat e = $buffet 
{
     hiddens =   2 
   outputs =  2
   inputs = 4
   gates = < !logic !logic >
}

__population Population = $linear 
{ 
  size = 50 
  entity = !e # `entity` is special
  track_lineage = true 
  load_from = ""
}

__process Process = $cycle  { 
 count = 11
  world = 
  $sequence  
  {
     first   =   $forager   
        { 
          ? food_eaten 2 
          line_of_sight : in_layer 
          action : out_layer 
        }
     second = $elite_replacement  {  strength = 0.5  }
  }
}

