

# working

enc = $encoding 
{
	point_mutate_prob =  0.005 
}

e = $markov_brain_bf 
{
     hiddens =    2 
	 outputs =  2
	 inputs = 4
	 genome = !enc
}

Population = $linear 
{ 
	size = 50 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
}



fors = $sequence  
{
     first 	= 	$forager_bf 	
				{ 
				  ? food_eaten 5 
	 			  front_line_of_sight : front_in_sense 
	 			  back_line_of_sight : back_in_sense 
				}
     second = $elite_replacement  {  strength = 0.4  }
}


Process = $cycle  { 
 count = 101
  world = !fors
}

