

# no way to turn off mutations? :(

e = $markov_brain 
	{	
		outputs =  2 
		inputs =  4
	}

pop = $linear 
	{ 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
	}

correct_pop = !pop { size = 25 }

empty_pop = !pop { size = 1 }

P = [ !correct_pop !empty_pop ]
#P =  !empty_pop 

env = 	$forager 	
		{ 
		  ? food_eaten 1 
		  sensor_range = 4
		}

no_diff_selection = $sequence  
{
	 first = !env
     second = $elite_replacement  {  strength = 0.01  }
}


correct_env = $sequence  
{
	 first = !env
     second = $elite_replacement  {  strength = 0.4  }
}


E = $cycle  { 
 count = 1001
  world = [ !correct_env !no_diff_selection ]
}

