

e = $markov_brain 
{
     hiddens = 5
	 outputs = 2
	 inputs = ^fs-first-sensor_range
}

Population = $linear 
{ 
	size = 40
	entity = !e # `entity` is special
	track_lineage = true 
}


fs = 
  $sequence  
{
     first 	= $forager 
			{	 
			? food_eaten 5 
			sensor_range =  [ 2 3  ]
			}

     second = $elite_replacement { strength = 0.4 }
}


Process = $cycle  { 
  count = 50
  world = !fs 
}

