
# working
# tests signal conversion sequence

encoding enc = $encoding 
{
	point_mutate_prob =  0.005 
}

substrate e = $markov_brain
{
     #hiddens =   [ 2 3 4 ] 
     hiddens =    2
	 outputs =  2 
	 inputs = 4
	 genome = !enc
}

population Population = $linear 
{ 
	size = 50 
	entity = !e # `entity` is special
	track_lineage = true 
	load_from = ""
}



process fors = $sequence  
{
     first 	= 	$forager 	
				{ 
				? food_eaten 5 
				#action <- $vb_vd <- $vd_vb  <- out_sense 
				action <- $add { by = 2.0 } <- out_sense 
				line_of_sight ->  $vd_vb  -> $vb_vd -> in_sense 
				}
     second = $elite_replacement  {  strength = 0.4 }
}


process Process = $cycle  { 
 count = 101
  world = !fors
}

