
# working
# tests nested process with nested tags 

substrate e = $markov_brain {
     hiddens = 5
	 outputs = 2
	 inputs = 4
	}

population Population = $linear 
	{ 
	size = 40
	entity = !e # `entity` is special
	track_lineage = true 
	}

process rep_for = $replicate 
	{
		num = [ 2 3 4 ] 
		env = $forager 
				{ 
				? food_eaten 3 
				action <- out_sense 
				line_of_sight ->  in_sense 
				}
		? x 10 
	}
		
process fs = 
  $sequence  {
     first 	= !rep_for 
     second = $elite_replacement { 
 	 strength = 0.4   
  }
}


process Process = $cycle  { 
 count = 101
  world = !fs
}

